### ISSUE TITLE
Hidden fields with values not passing value

### ISSUE THREAD

**Issue by Tigerlady** [blueriver/MuraCMS#2367]
When using the form builder and selecting a hidden field  and adding a value to it the value doesn't get into the form.  For example I have built a form with form builder and have a hidden field called formtitle when you do a view source the field has no value

`<input name="formtitle" id="field-formtitle" value="" type="hidden">`

When i view it in the form builder it does show a value in the field.  
![form-builder](https://cloud.githubusercontent.com/assets/1850313/16995804/e0954c48-4e73-11e6-8e54-7e6b2584e237.jpg)

**Comment by mattlevine** [comment]
Are yo on Mura 7?  If you are you can update your site and core files and the issue should be fixed with this commit.

https://github.com/blueriver/MuraCMS/commit/c899f9d649ceeee5d624175f3c033aed9de38e4a

**Comment by Tigerlady** [comment]
Matt,  
Yes I am on version 7 and I just updated my core and site files to the latest version 6686
 is the version that shows in site and core now. However, it didn't seem to fix the issue.  

I am still not getting the value in the viewed page.  

Also if I try to put [mura]$.content('title')[/mura]  which is what I want the hidden value to actually have and save the form the value becomes blank when going back inside the form editor.  It removes this value. 

I use this as a trigger for sending various emails in the event handler since the update to 7.0 no longer works with sending emails based on the title of the page. 

I have found that if I manually generate a form (simple form, never simple by the way) and use the hidden field here then the emails will get sent.

**Comment by mattlevine** [comment]
I was able to reproduce the issue and see it start to work with the above commit.  Since the fix is in the mura.js can you double check that your retest was not using cache js?

**Comment by Tigerlady** [comment]
Matt,  When I did the update yesterday through the CMS it updated a lot of files but these were not part of them at 6:30 last night.  However, this morning i pulled directly from GitHub and then did a file compare.  The js files were different so I updated my site with the files pulled directly from Git and it now works.  

Thanks.

**Comment by Tigerlady** [comment]
One more thing.  I tried using a mura tag in the Value field.  of the hidden field.  when rendering it actually outputs the mura tag not what is supposed to be the content. 

[mura]$.content('title')[/mura]

**Comment by mattlevine** [comment]
OK, I confirm this issue.  I'l try and get it fixed ASAP.

**Comment by mattlevine** [comment]
Please update your site and core and retest.
