### ISSUE TITLE
Bug in create bundle causes breadcrumb issue after deploy

### ISSUE THREAD

**Issue by damien-git** [blueriver/MuraCMS#2628]
When a bundle is created, the entries for all sites are exported in the tapprovalassignments table. After deploy, the site ID is overriden and all these entries end up being used in the same site. A consequence is breadcrumbs where the Home entry is repeated many times (as many times as there were tapprovalassignments entries for Home in the table).
Related forum thread:
https://groups.google.com/forum/#!msg/mura-cms-developers/lQDzvK21SD0/KoOd6M0eEQAJ

**Comment by mattlevine** [comment]
Did you do a bundle deployment from one site and to another within the same Mura instance?
-Matt

**Comment by damien-git** [comment]
It was an export from a Mura 6 instance to a Mura 7 instance. So I actually don't know if the bug is still present in Mura 7. I did not maintain keys.

**Comment by mudassarhayee** [comment]
Just wondering if someone has figured this out?  I am having the same issue.

**Comment by mattlevine** [comment]
We have not yet.  Try creating a temp.cfm in your Mura root and running this code

```
<cfscript>
m=application.serviceFactory('m');
m.getBean("contentUtility").updateGlobalMaterializedPath(siteID='YOURSITEID);
</cfscript>
```

**Comment by mudassarhayee** [comment]
I've tried this and get the following error message:

500 ErrorThe serviceFactory method was not found.
Type:Object

**Comment by mattlevine** [comment]
Whoops try the above code that I've updated.  Even though if you are the same person that posted in the google group your problem is probably fixed by clearing out tapprovalassignments in the database for that site.

**Comment by mudassarhayee** [comment]
There was nothing in the tapprovalassignments table.  I've tried the above code and didn't seem to resolve it.

The code did seem to run, but it didn't fix the issue.

**Comment by mattlevine** [comment]
I would have to have access to your server to do some debugging in order to know what's going on.

**Comment by damien-git** [comment]
For what it's worth, we encountered the same problem again, and clearing the tapprovalassignments table fixed it. So this might be a different issue.
